### ISSUE TITLE
TWITTER_MEMBER_LIST

### ISSUE THREAD

**Issue by ichinoserino** [Nachtalb/HololiveSubs#2]
what is the TWITTER_MEMBER_LIST?
where can I find it, thank

**Comment by Nachtalb** [comment]
On Twitter you can create your own lists
![image](https://user-images.githubusercontent.com/9467802/158018787-38d98047-f836-4af9-aa81-443c2f06a3aa.png)

There I've just created a list with all hololive members: 
![image](https://user-images.githubusercontent.com/9467802/158018814-254ab21c-b0fe-4801-a34a-13c948a53404.png)

And the ID you can find in the URL of said list: 
![image](https://user-images.githubusercontent.com/9467802/158018831-b556e368-77a8-4b79-bc8b-1a07ae161780.png)
